In [2]:
import numpy as np
import pandas as pd

In [3]:
numpy_array = np.array([1,2,3,4])

In [4]:
print(type(numpy_array))
print(numpy_array)

<class 'numpy.ndarray'>
[1 2 3 4]


In [5]:
list_1 = [1, 2, 3, 4]
print(type(list_1))
print(list_1)

<class 'list'>
[1, 2, 3, 4]


In [10]:
list_01 = np.random.random((344, 2))

In [11]:
list_01

array([[0.48198054, 0.50723285],
       [0.09082801, 0.68279937],
       [0.7098686 , 0.30597853],
       [0.30742497, 0.49917555],
       [0.62697467, 0.79476091],
       [0.9007705 , 0.32353408],
       [0.55808237, 0.67659447],
       [0.7514599 , 0.24344136],
       [0.94747067, 0.34613897],
       [0.36101468, 0.49605206],
       [0.21075051, 0.89623344],
       [0.63327623, 0.89838349],
       [0.33446042, 0.48834751],
       [0.95413875, 0.69274031],
       [0.71430164, 0.42182136],
       [0.27196639, 0.37889971],
       [0.56609735, 0.78865454],
       [0.20491622, 0.48818414],
       [0.23800542, 0.84691008],
       [0.385536  , 0.12292197],
       [0.29315461, 0.37478359],
       [0.30037243, 0.76988518],
       [0.51971134, 0.74274191],
       [0.97825784, 0.81589221],
       [0.73180917, 0.27473962],
       [0.85549801, 0.72981244],
       [0.7180801 , 0.78614001],
       [0.77390626, 0.13494305],
       [0.79780332, 0.11405407],
       [0.05342829, 0.64811225],
       [0.

In [12]:
list_01.shape

(344, 2)

In [17]:
list_01.reshape(2, -1)

array([[0.48198054, 0.50723285, 0.09082801, 0.68279937, 0.7098686 ,
        0.30597853, 0.30742497, 0.49917555, 0.62697467, 0.79476091,
        0.9007705 , 0.32353408, 0.55808237, 0.67659447, 0.7514599 ,
        0.24344136, 0.94747067, 0.34613897, 0.36101468, 0.49605206,
        0.21075051, 0.89623344, 0.63327623, 0.89838349, 0.33446042,
        0.48834751, 0.95413875, 0.69274031, 0.71430164, 0.42182136,
        0.27196639, 0.37889971, 0.56609735, 0.78865454, 0.20491622,
        0.48818414, 0.23800542, 0.84691008, 0.385536  , 0.12292197,
        0.29315461, 0.37478359, 0.30037243, 0.76988518, 0.51971134,
        0.74274191, 0.97825784, 0.81589221, 0.73180917, 0.27473962,
        0.85549801, 0.72981244, 0.7180801 , 0.78614001, 0.77390626,
        0.13494305, 0.79780332, 0.11405407, 0.05342829, 0.64811225,
        0.23132319, 0.34727263, 0.8781904 , 0.57108571, 0.12372802,
        0.79788475, 0.00950001, 0.21052007, 0.0675532 , 0.26154173,
        0.75737625, 0.70466159, 0.49768222, 0.75

In [20]:
list2 = np.random.randint(0, 200, size=10)

In [21]:
list2

array([ 32, 183, 129, 191, 170,  38,  22, 175, 173, 164])